# Generated by Django 3.0.7 on 2020-12-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('itemid', models.AutoField(primary_key=True, serialize=False)),
                ('itemname', models.TextField()),
                ('description', models.TextField()),
                ('created_at', models.DateField()),
                ('password', models.CharField(max_length=255)),
                ('profile_image', models.ImageField(upload_to='')),
                ('country_code', models.TextField()),
            ],
        ),
    ]
