# Generated by Django 3.0.7 on 2020-12-10 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0002_remove_item_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='profile_image',
            new_name='image',
        ),
    ]
