# Generated by Django 3.0.7 on 2021-02-23 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade_search', '0002_delete_item'),
        ('Item', '0004_item_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='hub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trade_search.Hub'),
        ),
        migrations.AlterField(
            model_name='item',
            name='country_code',
            field=models.TextField(blank=True),
        ),
    ]
